language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - appDir=project/app/
  global:
    - setup=basic

matrix:
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

sudo: required

before_install:
  - travis_retry npm install -g npm@'>=2.14.0'
  - travis_retry composer self-update
  - npm install -g bower
  - npm install -g gulp

install:
  - cd $appDir
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

before_script:
  - cd $appDir
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'

script:
  - cd $appDir
  - vendor/bin/phpunit
